# Travis Build File
language: java
jdk:
  - oraclejdk8
before_install:
  - wget http://repo.spring.io/milestone/org/springframework/boot/spring-boot-dependencies/2.0.0.RC1/spring-boot-dependencies-2.0.0.RC1.pom
  - wget http://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-web/2.0.0.RC1/spring-boot-starter-web-2.0.0.RC1.jar
  - wget http://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-data-jpa/2.0.0.RC1/spring-boot-starter-data-jpa-2.0.0.RC1.jar
  - wget http://http://repo.spring.io/milestone/org/springframework/boot/spring-boot-starter-actuator/2.0.0.RC1/spring-boot-starter-actuator-2.0.0.RC1.jar
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean compile test
notifications:
  email:
    - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true